<a href="https://colab.research.google.com/github/siri-chandana-macha/Data_Science_Tasks/blob/main/CafeSales_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing libraries
import pandas as pd
import numpy as np

In [15]:
# load the dataset
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [16]:
#  Rename columns
d = {
    "Transaction ID": "transaction_id",
    "Price Per Unit": "price (per_unit)",
    "Transaction Date": "transaction_date"
}

df.rename(columns=d, inplace=True)
df.head()

,transaction_id,Item,Quantity,price (per_unit),Total Spent,Payment Method,Location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
#Drop Duplicate Rows
df.drop_duplicates(inplace=True)
df

,transaction_id,Item,Quantity,price (per_unit),Total Spent,Payment Method,Location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [6]:
#Handling Missing Values
df.isnull().sum()

transaction_id         0
Item                 333
Quantity             138
price (per_unit)     179
Total Spent          173
Payment Method      2579
Location            3265
transaction_date     159
dtype: int64

In [13]:
print("Unique values in 'Item' column:", df['Item'].unique())
print("Unique values in 'Quantity' column:", df['Quantity'].unique())
print("Unique values in 'Total Spent' column:", df['Total Spent'].unique())
print("Unique values in 'Payment Method' column:", df['Payment Method'].unique())
print("Unique values in 'Location' column:", df['Location'].unique())

Unique values in 'Item' column: ['Coffee' 'Salad' 'Sandwich' 'Juice' 'Smoothie' 'Cookie' 'Tea' 'Cake']
Unique values in 'Quantity' column: ['2' '5' '3' '4' '1']
Unique values in 'Total Spent' column: ['4.0' '25.0' '8.0' '15.0' '6.0' '12.0' '16.0' '20.0' '5.0' '10.0' '1.0'
 '3.0' '2.0' '9.0' '7.5' '4.5' '1.5']
Unique values in 'Payment Method' column: ['Digital Wallet' 'Cash' 'Credit Card']
Unique values in 'Location' column: ['In-store' 'Takeaway']

In [14]:
df.replace(['UNKNOWN', 'ERROR'], np.nan, inplace=True)

print("Updated unique values in 'Item' column:", df['Item'].unique())
print("Updated unique values in 'Quantity' column:", df['Quantity'].unique())
print("Updated unique values in 'Total Spent' column:", df['Total Spent'].unique())
print("Updated unique values in 'Payment Method' column:", df['Payment Method'].unique())
print("Updated unique values in 'Location' column:", df['Location'].unique())

df.isnull().sum()

Updated unique values in 'Item' column: ['Coffee' 'Salad' 'Sandwich' 'Juice' 'Smoothie' 'Cookie' 'Tea' 'Cake']
Updated unique values in 'Quantity' column: ['2' '5' '3' '4' '1']
Updated unique values in 'Total Spent' column: ['4.0' '25.0' '8.0' '15.0' '6.0' '12.0' '16.0' '20.0' '5.0' '10.0' '1.0'
 '3.0' '2.0' '9.0' '7.5' '4.5' '1.5']
Updated unique values in 'Payment Method' column: ['Digital Wallet' 'Cash' 'Credit Card']
Updated unique values in 'Location' column: ['In-store' 'Takeaway']

Item                0
Quantity            0
price (per_unit)    0
Total Spent         0
Payment Method      0
Location            0
transaction_date    0
dtype: int64

In [9]:
# Drop Missing Rows
df.dropna(inplace=True)
df

,transaction_id,Item,Quantity,price (per_unit),Total Spent,Payment Method,Location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
...,...,...,...,...,...,...,...,...
9975,TXN_9668108,Cake,1,3.0,3.0,Cash,In-store,2023-01-20
9979,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [10]:
# Dropping Unwanted Columns
df = df.drop(["transaction_id"], axis=1)

df.head()

,Item,Quantity,price (per_unit),Total Spent,Payment Method,Location,transaction_date
0,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
4,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03

In [11]:
#Dropping Unwanted Rows (By Index)
df = df.drop([0, 1])   # dropping first two rows
df.head()

,Item,Quantity,price (per_unit),Total Spent,Payment Method,Location,transaction_date
4,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
15,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
17,Juice,2,3.0,6.0,Cash,In-store,2023-02-24

In [12]:
#Resetting Index
df.reset_index(drop=True, inplace=True)
df.head()

,Item,Quantity,price (per_unit),Total Spent,Payment Method,Location,transaction_date
0,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
1,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
2,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
3,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
4,Juice,2,3.0,6.0,Cash,In-store,2023-02-24